
USE [master]
GO

/****** Object:  Database [Topic]    Script Date: 2018/1/9 下午 02:53:36 ******/
CREATE DATABASE [Topic]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Topic', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Topic.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Topic_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Topic_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Topic] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Topic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Topic] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Topic] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Topic] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Topic] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Topic] SET ARITHABORT OFF
GO

ALTER DATABASE [Topic] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Topic] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Topic] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Topic] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Topic] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Topic] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Topic] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Topic] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Topic] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Topic] SET  DISABLE_BROKER
GO

ALTER DATABASE [Topic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Topic] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Topic] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Topic] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Topic] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Topic] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Topic] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Topic] SET RECOVERY FULL
GO

ALTER DATABASE [Topic] SET  MULTI_USER
GO

ALTER DATABASE [Topic] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Topic] SET DB_CHAINING OFF
GO

ALTER DATABASE [Topic] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Topic] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Topic] SET DELAYED_DURABILITY = DISABLED
GO

EXEC sys.sp_db_vardecimal_storage_format N'Topic', N'ON'
GO

USE [Topic]
GO

/****** Object:  Table [dbo].[IngredientList]    Script Date: 2018/1/9 下午 02:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[OrderDetails]    Script Date: 2018/1/9 下午 02:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Orders]    Script Date: 2018/1/9 下午 02:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Recipes]    Script Date: 2018/1/9 下午 02:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[RecipesIngredient]    Script Date: 2018/1/9 下午 02:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Storage]    Script Date: 2018/1/9 下午 02:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[User]    Script Date: 2018/1/9 下午 02:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [Topic] SET  READ_WRITE
GO
